name: Python Package using Conda

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest  # Specifies that this job will run on Ubuntu
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true  # Ensure Conda is updated

    - name: Initialize Conda
      run: |
        conda init bash  # Initialize Conda for bash (on Ubuntu)
        source ~/.bashrc  # Source bashrc to apply conda init changes
        conda env create --name MESHING --file requirements.yml  # Create the environment
        conda activate MESHING  # Activate the Conda environment
        echo "Conda environment MESHING activated."
        python src/setup.py install  # Install the package using setup.py

    - name: Run tests
      run: |
        conda init bash  # Initialize Conda for bash (on Ubuntu)
        source ~/.bashrc  # Source bashrc to apply conda init changes
        conda activate MESHING  # Activate the Conda environment
        echo "Conda environment MESHING for testing activated."
        pip list
        python -c "import meshing; print(meshing.__version__)"  # Ensure the package is accessible
        pytest --maxfail=1 --disable-warnings -q  # Run pytest with options to limit output and failures
